# Generated by Django 2.2.3 on 2019-07-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kieFrontApp', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(0, 'Sedentary'), (1, 'Light'), (2, 'Moderate'), (3, 'Active'), (4, 'Very Active'), (5, 'Extra Active')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], default=0, null=True),
        ),
    ]
