# Generated by Django 2.2.3 on 2019-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kieFrontApp', '0004_user_cuisine_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='takes_beef',
            field=models.IntegerField(blank=True, choices=[(0, 'yes'), (1, 'no')], default=0, null=True),
        ),
    ]
